### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by ShinJoy991** [Rapha149/MessageHider#5]
Hi ,althougth i read the tutorial but still confusing. I just want to hide messages every time other plugins show (on all players). Example, I want to hide message "&2Some thing &4colorful".
 -  My problem is I dont know how to create a filter?
 -  I typed "/messagehider createcommand %mh_player_receiver_name%" and "/messagehider createcommand Myname" or "/messagehider createcommand %Myname%" according to this tutorial line:
 /messagehider createcommand <Filter> - Creates an empty command for a filter. 
    None of them worked, I received "[MH] Unknown filter."
 -  I saw many examples but what type of that file and where it can be placed?

**Comment by Rapha149** [comment]
So `createcommand` is not what you need. It's if you have already created a filter and want to add a command that is executed every time that filter is being activated.
What you want to do is `/messagehider create`. That command creates you an empty filter. But I didn't design the plugin to be interactive – maybe I would do that today but since there were a lot of changes in the 1.19.3 update I lost motivation to continue this plugin.

So, once you have executed that command, go to `plugins/MessageHider` and open the file `config.yml`. There you can edit the filter you created. What the different things mean is explained in the tutorial. If you have any further questions feel free to ask.

**Comment by ShinJoy991** [comment]
I tried copy "Preset: gamemode change" and "Preset: only self commands" but it not work, still get "Set own gamemode to Survival Mode" , do I need edit some thing? 
```
# version=2.1 DO NOT CHANGE THIS LINE
messageFilters:
- id: gamemode_change
  message:
    text: ''
    replace:
      enabled: false
      text: null
      type: null
      systemMessage: false
    ignoreCase: false
    type: null
    regex: false
    json:
      enabled: false
      jsonPrecisionLevel: 2
  onlyHideForOtherPlayers: false
  onlyExecuteCommands: false
  stopAfter: false
  priority: null
  commands: []
  targets:
    senders: []
    excludedSenders: []
    receivers: []
    excludedReceivers: []
prefix: '&8[&cMH&8] '
checkForUpdates: true
presets:
  idleTimeout: false
  gamemodeChange: false
  onlySelfCommands: false
  consoleCommands: false
```

**Comment by Rapha149** [comment]
What exactly did you copy? Because to me it looks just like an empty filter except for it's id.

**Comment by ShinJoy991** [comment]
Uh oh, sorry, I click copy button and paste but when reload /mh reload it disappear, I carefull copy only text line and check again, still not work, when /mh reload, the config not erase anything anymore, here is it.
```
# version=2.1 DO NOT CHANGE THIS LINE
messageFilters:
- id: gamemode_change
  message:
    text: '{"italic": true, "color": "gray", "translate": "chat\\.type\\.admin", "with": [{},{"translate": "commands\\.gamemode\\.success\\.\\w+"}]}'
    replace:
      enabled: false
      text: null
      type: null
      systemMessage: false
    ignoreCase: false
    type: null
    regex: false
    json:
      enabled: false
      jsonPrecisionLevel: 2
  onlyHideForOtherPlayers: false
  onlyExecuteCommands: false
  stopAfter: false
  priority: null
  commands: []
  targets:
    senders: []
    excludedSenders: []
    receivers: []
    excludedReceivers: []
prefix: '&8[&cMH&8] '
checkForUpdates: true
presets:
  idleTimeout: false
  gamemodeChange: false
  onlySelfCommands: false
  consoleCommands: false
```

**Comment by Rapha149** [comment]
The text for the gamemode change preset is using json, the json precision level 1 and regex, so you have to set these as well. 
Btw, that the file was overwritten could be because you used `/mh reload` before saving.

**Comment by ShinJoy991** [comment]
Can you show me an example for this gamemode change? Its easier to know an example.

**Comment by Rapha149** [comment]
Well this is the example from the tutorial 🤷

```yml
id: gamemode_change
message:
  text: '{"italic": true, "color": "gray", "translate": "chat\\.type\\.admin", "with": [{},{"translate": "commands\\.gamemode\\.success\\.\\w+"}]}'
  replace:
    enabled: false
    text: null
    type: null
    systemMessage: false
  ignoreCase: false
  type: null
  regex: true
  json:
    enabled: true
    jsonPrecisionLevel: 1
onlyHideForOtherPlayers: false
onlyExecuteCommands: false
stopAfter: false
priority: null
commands: [ ]
targets:
  excludedReceivers: [ ]
  excludedSenders: [ ]
  receivers: [ ]
  senders: [ ]
```
